[package]
name = "kora"
version = "0.1.0"
authors = ["CRGK"]
edition = "2018"

# cargo build
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "PleaseWork"
path = "src/bin/PleaseWork.rs"

[dependencies]
curve25519-dalek = { version = "3", features = ["serde"] }
rand = "0.7.3"
serde = { version = "1.0", features = ["derive"] }
sha3 = "0.9.1"
merlin = "3.0.0"
rayon = "1.5.0"
byteorder = "1"
aes-gcm-siv = "0.10.2"
hmac = "0.10.1"
bytes = "0.5.6"
serde_cbor = "0.11.1"
serde_json = "1.0.59"
bincode = "1"
bit-vec = "0.6.3"
modinverse = "0.1.1"
polynomial-over-finite-prime-field = "0.3.1"
ahash = "0.7.4"